#include "PackingApp.h"
#include "data/CalendarStore.h"
#include "hardware/HapticService.h"
#include "hardware/RTCService.h"
#include "ui/FormWidgets.h"
#include "ui/Theme.h"
#include <Arduino.h>
#include <cstdio>
#include <cstring>
#include <time.h>

void PackingApp::create(lv_obj_t*p){root_=lv_obj_create(p);lv_obj_set_size(root_,LV_PCT(100),LV_PCT(100));lv_obj_set_style_pad_all(root_,5,0);lv_obj_set_style_border_width(root_,0,0);lv_obj_set_style_radius(root_,0,0);lv_obj_set_scrollable(root_,false);if(view_==View::Editor&&hasDraft_)showEditor(editingId_);else if(view_==View::List)showList();else showPack();}
void PackingApp::suspend(){if(view_==View::Editor)capture();}void PackingApp::destroy(){if(root_){lv_obj_delete(root_);root_=nullptr;}keyword_=title_=items_=nullptr;}
void PackingApp::showPack(){view_=View::Pack;lv_obj_clean(root_);struct tm now{};rtc_.now(now);time_t current=mktime(&now);calendar_.ensureWindowForDate(now.tm_year+1900,now.tm_mon+1,now.tm_mday);const CalendarEvent*best=nullptr;time_t bestAt=0;int by=0,bm=0,bd=0;for(int offset=0;offset<14;++offset){struct tm day=now;day.tm_mday+=offset;day.tm_hour=12;day.tm_min=0;day.tm_sec=0;mktime(&day);for(size_t i=0;i<calendar_.count();++i){const auto&e=calendar_.at(i);if(!calendar_.occursOn(e,day.tm_year+1900,day.tm_mon+1,day.tm_mday))continue;struct tm start=day;start.tm_hour=e.startHour;start.tm_min=e.startMinute;start.tm_sec=0;time_t at=mktime(&start);if(at>current&&(!best||at<bestAt)){best=&e;bestAt=at;by=start.tm_year+1900;bm=start.tm_mon+1;bd=start.tm_mday;}}}
    lv_obj_t*h=lv_label_create(root_);lv_label_set_text(h,"PACK FOR NEXT");lv_obj_set_style_text_font(h,&lv_font_montserrat_20,0);lv_obj_set_pos(h,3,3);auto*manage=FormWidgets::button(root_,"TEMPLATES",365,0,104,32);lv_obj_add_event_cb(manage,templatesClicked,LV_EVENT_CLICKED,this);
    if(!best){auto*l=lv_label_create(root_);lv_label_set_text(l,"No upcoming calendar event in the next 14 days.");lv_obj_center(l);return;}char event[90];snprintf(event,sizeof(event),"%s  |  %02d/%02d %02u:%02u",best->title,bd,bm,best->startHour,best->startMinute);auto*e=lv_label_create(root_);lv_label_set_text(e,event);lv_obj_set_width(e,455);lv_label_set_long_mode(e,LV_LABEL_LONG_DOT);lv_obj_set_pos(e,4,38);
    auto*packing=store_.match(best->title);if(!packing){auto*l=lv_label_create(root_);lv_label_set_text(l,"No matching packing template.\nCreate one using a word from the lesson name.");lv_obj_set_style_text_align(l,LV_TEXT_ALIGN_CENTER,0);lv_obj_center(l);return;}const uint64_t key=(static_cast<uint64_t>(best->id)<<32)|static_cast<uint32_t>(by*10000+bm*100+bd);PackingState loaded{};if(!store_.loadState(loaded)||loaded.occurrenceKey!=key){state_={};state_.occurrenceKey=key;store_.saveState(state_);}else state_=loaded;
    auto*t=lv_label_create(root_);lv_label_set_text(t,packing->title);lv_obj_set_style_text_color(t,Theme::color(0x1E6675),0);lv_obj_set_style_text_font(t,&lv_font_montserrat_16,0);lv_obj_set_pos(t,4,63);
    for(uint8_t i=0;i<packing->itemCount;++i){auto*c=lv_checkbox_create(root_);lv_checkbox_set_text(c,packing->items[i]);lv_obj_set_pos(c,10+(i%2)*230,91+(i/2)*29);if(state_.checkedMask&(1u<<i))lv_obj_add_state(c,LV_STATE_CHECKED);lv_obj_set_user_data(c,reinterpret_cast<void*>(static_cast<uintptr_t>(i)));lv_obj_add_event_cb(c,itemChecked,LV_EVENT_VALUE_CHANGED,this);}
}
void PackingApp::showList(){view_=View::List;hasDraft_=false;lv_obj_clean(root_);auto*h=lv_label_create(root_);lv_label_set_text(h,"PACKING TEMPLATES");lv_obj_set_style_text_font(h,&lv_font_montserrat_20,0);lv_obj_set_pos(h,3,3);auto*add=FormWidgets::button(root_,"+ NEW",365,0,104,32,true);lv_obj_add_event_cb(add,addClicked,LV_EVENT_CLICKED,this);auto*back=FormWidgets::button(root_,"PACK",275,0,84,32);lv_obj_add_event_cb(back,backPackClicked,LV_EVENT_CLICKED,this);auto*list=lv_obj_create(root_);lv_obj_set_pos(list,0,40);lv_obj_set_size(list,469,144);lv_obj_set_flex_flow(list,LV_FLEX_FLOW_COLUMN);lv_obj_set_style_pad_all(list,3,0);for(size_t i=0;i<store_.count();++i){auto&r=store_.at(i);auto*b=lv_button_create(list);Theme::styleButton(b,i==0);lv_obj_set_width(b,LV_PCT(100));lv_obj_set_height(b,38);lv_obj_set_user_data(b,reinterpret_cast<void*>(static_cast<uintptr_t>(r.id)));lv_obj_add_event_cb(b,templateClicked,LV_EVENT_CLICKED,this);auto*l=lv_label_create(b);char text[80];snprintf(text,sizeof(text),"%s  -  matches '%s'",r.title,r.keyword);lv_label_set_text(l,text);lv_obj_align(l,LV_ALIGN_LEFT_MID,0,0);}}
void PackingApp::showEditor(uint32_t id){view_=View::Editor;editingId_=id;lv_obj_clean(root_);if(!hasDraft_){draft_={};if(id){if(auto*f=store_.find(id))draft_=*f;}hasDraft_=true;}keyword_=FormWidgets::text(root_,"Lesson word e.g. Physical",0,0,230,38);title_=FormWidgets::text(root_,"List name e.g. PE KIT",239,0,230,38);items_=FormWidgets::text(root_,"One item per line (up to 6)",0,45,469,82,false);lv_textarea_set_text(keyword_,draft_.keyword);lv_textarea_set_text(title_,draft_.title);char items[210]{};for(uint8_t i=0;i<draft_.itemCount;++i){if(i)strlcat(items,"\n",sizeof(items));strlcat(items,draft_.items[i],sizeof(items));}lv_textarea_set_text(items_,items);auto*save=FormWidgets::button(root_,"SAVE",0,135,120,42,true);lv_obj_add_event_cb(save,saveClicked,LV_EVENT_CLICKED,this);auto*back=FormWidgets::button(root_,"BACK",128,135,100,42);lv_obj_add_event_cb(back,backListClicked,LV_EVENT_CLICKED,this);if(id){auto*del=FormWidgets::button(root_,"DELETE",349,135,120,42);lv_obj_add_event_cb(del,deleteClicked,LV_EVENT_CLICKED,this);}lv_group_focus_obj(keyword_);}
void PackingApp::capture(){if(!keyword_)return;strlcpy(draft_.keyword,lv_textarea_get_text(keyword_),sizeof(draft_.keyword));strlcpy(draft_.title,lv_textarea_get_text(title_),sizeof(draft_.title));draft_.itemCount=0;char b[210];strlcpy(b,lv_textarea_get_text(items_),sizeof(b));for(char*l=strtok(b,"\n");l&&draft_.itemCount<6;l=strtok(nullptr,"\n")){while(*l==' ')++l;if(*l)strlcpy(draft_.items[draft_.itemCount++],l,32);}hasDraft_=true;}
void PackingApp::templatesClicked(lv_event_t*e){static_cast<PackingApp*>(lv_event_get_user_data(e))->showList();}void PackingApp::itemChecked(lv_event_t*e){auto*s=static_cast<PackingApp*>(lv_event_get_user_data(e));uint8_t i=reinterpret_cast<uintptr_t>(lv_obj_get_user_data(lv_event_get_target_obj(e)));if(lv_obj_has_state(lv_event_get_target_obj(e),LV_STATE_CHECKED))s->state_.checkedMask|=1u<<i;else s->state_.checkedMask&=~(1u<<i);s->store_.saveState(s->state_);s->haptic_.play(1);}void PackingApp::templateClicked(lv_event_t*e){auto*s=static_cast<PackingApp*>(lv_event_get_user_data(e));s->hasDraft_=false;s->showEditor(reinterpret_cast<uintptr_t>(lv_obj_get_user_data(lv_event_get_target_obj(e))));}void PackingApp::addClicked(lv_event_t*e){auto*s=static_cast<PackingApp*>(lv_event_get_user_data(e));s->hasDraft_=false;s->showEditor(0);}void PackingApp::saveClicked(lv_event_t*e){auto*s=static_cast<PackingApp*>(lv_event_get_user_data(e));s->capture();if(s->draft_.keyword[0]&&s->draft_.title[0]&&s->draft_.itemCount){s->draft_.id=s->editingId_;if(s->store_.upsert(s->draft_))s->showList();}}void PackingApp::backPackClicked(lv_event_t*e){static_cast<PackingApp*>(lv_event_get_user_data(e))->showPack();}void PackingApp::backListClicked(lv_event_t*e){static_cast<PackingApp*>(lv_event_get_user_data(e))->showList();}void PackingApp::deleteClicked(lv_event_t*e){auto*s=static_cast<PackingApp*>(lv_event_get_user_data(e));s->store_.remove(s->editingId_);s->showList();}
