#include "NotesApp.h"
#include "ui/FormWidgets.h"
#include "ui/Theme.h"
#include <Arduino.h>
#include <cstdio>

void NotesApp::create(lv_obj_t*parent){root_=lv_obj_create(parent);lv_obj_set_size(root_,LV_PCT(100),LV_PCT(100));lv_obj_set_style_pad_all(root_,5,0);lv_obj_set_style_border_width(root_,0,0);lv_obj_set_style_radius(root_,0,0);lv_obj_set_scrollable(root_,false);if(view_==View::Editor&&hasDraft_)showEditor(editingId_);else showList();}
void NotesApp::suspend(){if(view_==View::Editor)capture();}
void NotesApp::destroy(){if(root_){lv_obj_delete(root_);root_=nullptr;}titleField_=bodyField_=nullptr;}
void NotesApp::showList(){view_=View::List;hasDraft_=false;lv_obj_clean(root_);lv_obj_t*h=lv_label_create(root_);lv_label_set_text(h,"NOTES");lv_obj_set_style_text_font(h,&lv_font_montserrat_20,0);lv_obj_set_pos(h,5,5);auto*add=FormWidgets::button(root_,"+ NOTE",365,0,104,34,true);lv_obj_add_event_cb(add,newClicked,LV_EVENT_CLICKED,this);lv_obj_t*list=lv_obj_create(root_);lv_obj_set_pos(list,0,40);lv_obj_set_size(list,469,144);lv_obj_set_flex_flow(list,LV_FLEX_FLOW_COLUMN);lv_obj_set_style_pad_all(list,3,0);lv_obj_set_style_pad_row(list,4,0);lv_obj_set_style_border_width(list,0,0);if(!store_.count()){lv_obj_t*empty=lv_label_create(list);lv_label_set_text(empty,"No notes - press + NOTE");lv_obj_set_style_text_color(empty,Theme::color(0x6C716F),0);lv_obj_center(empty);return;}for(size_t i=0;i<store_.count();++i){const auto&n=store_.at(i);lv_obj_t*b=lv_button_create(list);Theme::styleButton(b,i==0);lv_obj_set_width(b,LV_PCT(100));lv_obj_set_height(b,38);lv_obj_set_user_data(b,reinterpret_cast<void*>(static_cast<uintptr_t>(n.id)));lv_obj_add_event_cb(b,itemClicked,LV_EVENT_CLICKED,this);lv_obj_t*l=lv_label_create(b);lv_label_set_text(l,n.title[0]?n.title:"Untitled note");lv_obj_set_style_text_font(l,&lv_font_montserrat_14,0);lv_obj_align(l,LV_ALIGN_LEFT_MID,0,0);}}
void NotesApp::showEditor(uint32_t id){view_=View::Editor;editingId_=id;lv_obj_clean(root_);if(!hasDraft_){draft_={};body_[0]=0;if(id){auto*n=store_.find(id);if(n)draft_=*n;store_.readBody(id,body_,sizeof(body_));}hasDraft_=true;}titleField_=FormWidgets::text(root_,"Note title",0,0,469,36);bodyField_=FormWidgets::text(root_,"Start typing...",0,41,469,99,false);lv_textarea_set_max_length(bodyField_,sizeof(body_)-1);lv_textarea_set_text(titleField_,draft_.title);lv_textarea_set_text(bodyField_,body_);auto*save=FormWidgets::button(root_,"SAVE",0,146,120,38,true);lv_obj_add_event_cb(save,saveClicked,LV_EVENT_CLICKED,this);auto*back=FormWidgets::button(root_,"BACK",128,146,100,38);lv_obj_add_event_cb(back,backClicked,LV_EVENT_CLICKED,this);if(id){auto*del=FormWidgets::button(root_,"DELETE",349,146,120,38);lv_obj_add_event_cb(del,deleteClicked,LV_EVENT_CLICKED,this);}lv_group_focus_obj(titleField_);}
void NotesApp::capture(){if(!titleField_)return;strlcpy(draft_.title,lv_textarea_get_text(titleField_),sizeof(draft_.title));strlcpy(body_,lv_textarea_get_text(bodyField_),sizeof(body_));hasDraft_=true;}
void NotesApp::newClicked(lv_event_t*e){static_cast<NotesApp*>(lv_event_get_user_data(e))->showEditor(0);}void NotesApp::itemClicked(lv_event_t*e){auto*s=static_cast<NotesApp*>(lv_event_get_user_data(e));s->hasDraft_=false;s->showEditor(static_cast<uint32_t>(reinterpret_cast<uintptr_t>(lv_obj_get_user_data(lv_event_get_target_obj(e)))));}void NotesApp::saveClicked(lv_event_t*e){auto*s=static_cast<NotesApp*>(lv_event_get_user_data(e));s->capture();if(!s->draft_.title[0])strlcpy(s->draft_.title,"Untitled note",sizeof(s->draft_.title));s->draft_.id=s->editingId_;if(s->store_.upsert(s->draft_,s->body_))s->showList();}void NotesApp::deleteClicked(lv_event_t*e){auto*s=static_cast<NotesApp*>(lv_event_get_user_data(e));s->store_.remove(s->editingId_);s->showList();}void NotesApp::backClicked(lv_event_t*e){static_cast<NotesApp*>(lv_event_get_user_data(e))->showList();}
