#include "TasksApp.h"
#include "hardware/RTCService.h"
#include "ui/FormWidgets.h"
#include "ui/Theme.h"
#include <Arduino.h>
#include <cstdio>
#include <cstdlib>

void TasksApp::create(lv_obj_t*parent){root_=lv_obj_create(parent);lv_obj_set_size(root_,LV_PCT(100),LV_PCT(100));lv_obj_set_style_pad_all(root_,5,0);lv_obj_set_style_border_width(root_,0,0);lv_obj_set_style_radius(root_,0,0);lv_obj_set_scrollable(root_,false);if(view_==View::Editor&&hasDraft_)showEditor(editingId_);else showList();}
void TasksApp::suspend(){if(view_==View::Editor)capture();}
void TasksApp::destroy(){if(root_){lv_obj_delete(root_);root_=nullptr;}titleField_=notesField_=dueField_=reminderField_=priorityField_=recurringField_=nullptr;}
void TasksApp::showList(){view_=View::List;hasDraft_=false;lv_obj_clean(root_);lv_obj_t*h=lv_label_create(root_);lv_label_set_text(h,"TASKS");lv_obj_set_style_text_font(h,&lv_font_montserrat_20,0);lv_obj_set_pos(h,5,5);auto*add=FormWidgets::button(root_,"+ TASK",365,0,104,34,true);lv_obj_add_event_cb(add,newClicked,LV_EVENT_CLICKED,this);lv_obj_t*list=lv_obj_create(root_);lv_obj_set_pos(list,0,40);lv_obj_set_size(list,469,144);lv_obj_set_flex_flow(list,LV_FLEX_FLOW_COLUMN);lv_obj_set_style_pad_all(list,3,0);lv_obj_set_style_pad_row(list,4,0);lv_obj_set_style_border_width(list,0,0);
    if(!store_.count()){lv_obj_t*empty=lv_label_create(list);lv_label_set_text(empty,"Nothing pending - press + TASK");lv_obj_set_style_text_color(empty,Theme::color(0x6C716F),0);lv_obj_center(empty);return;}
    for(size_t i=0;i<store_.count();++i){const auto&r=store_.at(i);lv_obj_t*row=lv_obj_create(list);lv_obj_set_width(row,LV_PCT(100));lv_obj_set_height(row,40);lv_obj_set_style_pad_all(row,2,0);lv_obj_set_style_border_width(row,0,0);lv_obj_set_scrollable(row,false);lv_obj_t*check=lv_checkbox_create(row);lv_checkbox_set_text(check,"");lv_obj_align(check,LV_ALIGN_LEFT_MID,2,0);if(r.completed)lv_obj_add_state(check,LV_STATE_CHECKED);lv_obj_set_user_data(check,reinterpret_cast<void*>(static_cast<uintptr_t>(r.id)));lv_obj_add_event_cb(check,completedChanged,LV_EVENT_VALUE_CHANGED,this);lv_obj_t*b=lv_button_create(row);Theme::styleButton(b,false);lv_obj_set_size(b,410,36);lv_obj_align(b,LV_ALIGN_RIGHT_MID,0,0);lv_obj_set_user_data(b,reinterpret_cast<void*>(static_cast<uintptr_t>(r.id)));lv_obj_add_event_cb(b,itemClicked,LV_EVENT_CLICKED,this);char line[112];const char*p=r.priority==2?"! ":r.priority==0?"- ":"";if(r.dueYear)snprintf(line,sizeof(line),"%s%s   %04d-%02u-%02u%s",p,r.title,r.dueYear,r.dueMonth,r.dueDay,r.recurring?"  [W]":"");else snprintf(line,sizeof(line),"%s%s%s",p,r.title,r.recurring?"  [W]":"");lv_obj_t*l=lv_label_create(b);lv_label_set_text(l,line);lv_obj_set_style_text_font(l,&lv_font_montserrat_14,0);lv_obj_set_style_text_decor(l,r.completed?LV_TEXT_DECOR_STRIKETHROUGH:LV_TEXT_DECOR_NONE,0);lv_obj_align(l,LV_ALIGN_LEFT_MID,0,0);}
}
void TasksApp::showEditor(uint32_t id){view_=View::Editor;editingId_=id;lv_obj_clean(root_);if(!hasDraft_){draft_={};struct tm now{};rtc_.now(now);draft_.dueYear=now.tm_year+1900;draft_.dueMonth=now.tm_mon+1;draft_.dueDay=now.tm_mday;draft_.priority=1;if(id){auto*r=store_.find(id);if(r)draft_=*r;}hasDraft_=true;}titleField_=FormWidgets::text(root_,"Task title",0,0,275,38);dueField_=FormWidgets::text(root_,"Due YYYY-MM-DD",280,0,189,38);notesField_=FormWidgets::text(root_,"Optional notes",0,44,275,67,false);reminderField_=lv_checkbox_create(root_);lv_checkbox_set_text(reminderField_,"Reminder 09:00");lv_obj_set_pos(reminderField_,290,50);recurringField_=lv_checkbox_create(root_);lv_checkbox_set_text(recurringField_,"Weekly");lv_obj_set_pos(recurringField_,290,78);priorityField_=lv_dropdown_create(root_);lv_dropdown_set_options(priorityField_,"Low\nNormal\nHigh");lv_obj_set_size(priorityField_,120,34);lv_obj_set_pos(priorityField_,0,119);lv_dropdown_set_selected(priorityField_,draft_.priority);lv_textarea_set_text(titleField_,draft_.title);lv_textarea_set_text(notesField_,draft_.notes);char date[20];snprintf(date,sizeof(date),"%04d-%02u-%02u",draft_.dueYear,draft_.dueMonth,draft_.dueDay);lv_textarea_set_text(dueField_,date);if(draft_.reminder)lv_obj_add_state(reminderField_,LV_STATE_CHECKED);if(draft_.recurring)lv_obj_add_state(recurringField_,LV_STATE_CHECKED);auto*save=FormWidgets::button(root_,"SAVE",130,119,105,45,true);lv_obj_add_event_cb(save,saveClicked,LV_EVENT_CLICKED,this);auto*back=FormWidgets::button(root_,"BACK",242,119,90,45);lv_obj_add_event_cb(back,backClicked,LV_EVENT_CLICKED,this);if(id){auto*del=FormWidgets::button(root_,"DELETE",349,119,120,45);lv_obj_add_event_cb(del,deleteClicked,LV_EVENT_CLICKED,this);}lv_group_focus_obj(titleField_);}
void TasksApp::capture(){if(!titleField_)return;strlcpy(draft_.title,lv_textarea_get_text(titleField_),sizeof(draft_.title));strlcpy(draft_.notes,lv_textarea_get_text(notesField_),sizeof(draft_.notes));parse();hasDraft_=true;}
bool TasksApp::parse(){int y,m,d;if(sscanf(lv_textarea_get_text(dueField_),"%d-%d-%d",&y,&m,&d)!=3||y<2020||m<1||m>12||d<1||d>31)return false;draft_.dueYear=y;draft_.dueMonth=m;draft_.dueDay=d;draft_.priority=lv_dropdown_get_selected(priorityField_);draft_.reminder=lv_obj_has_state(reminderField_,LV_STATE_CHECKED);draft_.recurring=lv_obj_has_state(recurringField_,LV_STATE_CHECKED);return true;}
void TasksApp::newClicked(lv_event_t*e){static_cast<TasksApp*>(lv_event_get_user_data(e))->showEditor(0);}void TasksApp::itemClicked(lv_event_t*e){auto*s=static_cast<TasksApp*>(lv_event_get_user_data(e));s->hasDraft_=false;s->showEditor(static_cast<uint32_t>(reinterpret_cast<uintptr_t>(lv_obj_get_user_data(lv_event_get_target_obj(e)))));}void TasksApp::completedChanged(lv_event_t*e){auto*s=static_cast<TasksApp*>(lv_event_get_user_data(e));auto*t=lv_event_get_target_obj(e);const uint32_t id=static_cast<uint32_t>(reinterpret_cast<uintptr_t>(lv_obj_get_user_data(t)));const bool checked=lv_obj_has_state(t,LV_STATE_CHECKED);auto*r=s->store_.find(id);const bool rollsForward=r&&r->recurring&&checked;s->store_.setCompleted(id,checked);if(rollsForward)lv_obj_remove_state(t,LV_STATE_CHECKED);}
void TasksApp::saveClicked(lv_event_t*e){auto*s=static_cast<TasksApp*>(lv_event_get_user_data(e));s->capture();if(s->draft_.title[0]&&s->parse()){s->draft_.id=s->editingId_;s->store_.upsert(s->draft_);s->showList();}}void TasksApp::deleteClicked(lv_event_t*e){auto*s=static_cast<TasksApp*>(lv_event_get_user_data(e));s->store_.remove(s->editingId_);s->showList();}void TasksApp::backClicked(lv_event_t*e){static_cast<TasksApp*>(lv_event_get_user_data(e))->showList();}
