#include "MessagingProtocol.h"
#include <Arduino.h>
#include <mbedtls/gcm.h>
#include <mbedtls/md.h>
#include <mbedtls/sha256.h>
#include <cstring>
namespace MessagingProtocol { namespace {
void put16(uint8_t*p,uint16_t v){p[0]=v>>8;p[1]=v;}void put32(uint8_t*p,uint32_t v){for(int i=0;i<4;++i)p[i]=v>>(24-i*8);}void put64(uint8_t*p,uint64_t v){for(int i=0;i<8;++i)p[i]=v>>(56-i*8);}uint16_t get16(const uint8_t*p){return(uint16_t(p[0])<<8)|p[1];}uint32_t get32(const uint8_t*p){uint32_t v=0;for(int i=0;i<4;++i)v=(v<<8)|p[i];return v;}uint64_t get64(const uint8_t*p){uint64_t v=0;for(int i=0;i<8;++i)v=(v<<8)|p[i];return v;}
void writeHeader(const Header&h,uint8_t*p){put16(p,kMagic);p[2]=kVersion;p[3]=uint8_t(h.type);put64(p+4,h.sender);put64(p+12,h.recipient);put32(p+20,h.messageId);put32(p+24,h.counter);put16(p+28,h.payloadLength);}
void nonceFor(const Header&h,uint8_t n[12]){put64(n,h.sender);put32(n+8,h.counter);}
bool hmac(const uint8_t key[32],const uint8_t*data,size_t length,uint8_t out[32]){const mbedtls_md_info_t*info=mbedtls_md_info_from_type(MBEDTLS_MD_SHA256);return info&&mbedtls_md_hmac(info,key,32,data,length,out)==0;}
}
bool inspectHeader(const uint8_t*p,size_t n,Header&h){if(!p||n<kHeaderSize||get16(p)!=kMagic||p[2]!=kVersion)return false;h.type=Type(p[3]);if(uint8_t(h.type)<1||uint8_t(h.type)>4)return false;h.sender=get64(p+4);h.recipient=get64(p+12);h.messageId=get32(p+20);h.counter=get32(p+24);h.payloadLength=get16(p+28);return h.sender&&h.payloadLength<=kMaxText;}
bool encodeEncrypted(const Header&input,const uint8_t key[32],const uint8_t*plain,size_t length,uint8_t*out,size_t cap,size_t&outLength){if(!key||!out||length>kMaxText||cap<kHeaderSize+length+kTagSize)return false;Header h=input;h.payloadLength=length;writeHeader(h,out);uint8_t nonce[12];nonceFor(h,nonce);const uint8_t empty=0;const uint8_t*inputData=length?plain:&empty;mbedtls_gcm_context ctx;mbedtls_gcm_init(&ctx);bool ok=mbedtls_gcm_setkey(&ctx,MBEDTLS_CIPHER_ID_AES,key,256)==0&&mbedtls_gcm_crypt_and_tag(&ctx,MBEDTLS_GCM_ENCRYPT,length,nonce,sizeof(nonce),out,kHeaderSize,inputData,out+kHeaderSize,kTagSize,out+kHeaderSize+length)==0;mbedtls_gcm_free(&ctx);outLength=ok?kHeaderSize+length+kTagSize:0;return ok;}
bool decodeEncrypted(const uint8_t*p,size_t n,const uint8_t key[32],Header&h,uint8_t*plain,size_t cap,size_t&plainLength){if(!inspectHeader(p,n,h)||h.type==Type::PairHello||h.payloadLength>cap||n!=kHeaderSize+h.payloadLength+kTagSize)return false;uint8_t nonce[12];nonceFor(h,nonce);mbedtls_gcm_context ctx;mbedtls_gcm_init(&ctx);bool ok=mbedtls_gcm_setkey(&ctx,MBEDTLS_CIPHER_ID_AES,key,256)==0&&mbedtls_gcm_auth_decrypt(&ctx,h.payloadLength,nonce,sizeof(nonce),p,kHeaderSize,p+kHeaderSize+h.payloadLength,kTagSize,p+kHeaderSize,plain)==0;mbedtls_gcm_free(&ctx);plainLength=ok?h.payloadLength:0;return ok;}
void derivePairKey(const char*code,uint64_t a,uint64_t b,uint8_t key[32]){if(a>b){uint64_t t=a;a=b;b=t;}uint8_t input[64]{};const char*label="PocketPDA pair v1";size_t used=strlcpy(reinterpret_cast<char*>(input),label,sizeof(input));size_t c=strnlen(code?code:"",24);memcpy(input+used,code?code:"",c);used+=c;put64(input+used,a);used+=8;put64(input+used,b);used+=8;mbedtls_sha256(input,used,key,0);}
bool encodePairHello(uint64_t sender,const char*name,const char*code,uint8_t*out,size_t cap,size_t&outLength){constexpr size_t payload=24+16;if(cap<kHeaderSize+payload)return false;Header h{Type::PairHello,sender,0,0,0,payload};writeHeader(h,out);memset(out+kHeaderSize,0,24);strncpy(reinterpret_cast<char*>(out+kHeaderSize),name?name:"PocketPDA",23);uint8_t key[32],proof[32];derivePairKey(code,sender,0,key);hmac(key,out,kHeaderSize+24,proof);memcpy(out+kHeaderSize+24,proof,16);outLength=kHeaderSize+payload;return true;}
bool decodePairHello(const uint8_t*p,size_t n,const char*code,Header&h,char*name,size_t nameCap,uint8_t key[32]){if(!inspectHeader(p,n,h)||h.type!=Type::PairHello||h.recipient||h.payloadLength!=40||n!=kHeaderSize+40||!name||!nameCap)return false;uint8_t helloKey[32],proof[32];derivePairKey(code,h.sender,0,helloKey);if(!hmac(helloKey,p,kHeaderSize+24,proof)||memcmp(proof,p+kHeaderSize+24,16)!=0)return false;derivePairKey(code,h.sender,ESP.getEfuseMac(),key);size_t copy=nameCap-1;if(copy>23)copy=23;memcpy(name,p+kHeaderSize,copy);name[copy]=0;return true;}
}
