#include "MessagingService.h"
#include "data/MessageStore.h"
#include "data/MessagingSettingsStore.h"
#include "hardware/HardwareManager.h"
#include "hardware/RTCService.h"
#include "ui/Shell.h"
#include <Arduino.h>
#include <LilyGoLib.h>
#include <RadioLib.h>
#include <cstring>

volatile bool MessagingService::irq_=false; MessagingService*MessagingService::active_=nullptr;
void MessagingService::radioIrq(){irq_=true;}
bool MessagingService::processorSleepReady() const {
    // Veto rather than postponing ACKs, pairing, retry timers or queued sends.
    // Physical DIO1 also covers a packet arriving before its ISR can run.
    return !irq_ && !digitalRead(LORA_IRQ) && state_==State::Receiving &&
        !suspended_ && !pairing_ && !ackPending_ && !currentLocalId_ &&
        messages_ && !messages_->nextPending();
}
void MessagingService::latchProcessorWake() {
    // An edge may occur while CPU interrupt delivery is masked for sleep.
    // SX1262 DIO1 stays asserted until readData clears it. Never clear IRQ here,
    // restart RX or touch the packet buffer; the existing onIrq path owns that.
    if(digitalRead(LORA_IRQ))irq_=true;
}
RadioRuntimeStats MessagingService::stats()const{RadioRuntimeStats value=stats_;const uint32_t elapsed=millis()-stateSince_;if(state_==State::Receiving)value.receiveMs+=elapsed;else if(state_==State::Transmitting)value.transmitMs+=elapsed;else if(state_==State::Sleeping)value.sleepMs+=elapsed;return value;}
uint32_t MessagingService::nowEpoch(){struct tm t{};if(!rtc_||!rtc_->now(t))return millis()/1000;return static_cast<uint32_t>(mktime(&t));}
void MessagingService::setState(State next){uint32_t now=millis(),elapsed=now-stateSince_;if(state_==State::Receiving)stats_.receiveMs+=elapsed;else if(state_==State::Transmitting)stats_.transmitMs+=elapsed;else if(state_==State::Sleeping)stats_.sleepMs+=elapsed;state_=next;stateSince_=now;}
bool MessagingService::begin(HardwareManager&hw,MessageStore&messages,MessagingSettingsStore&settings,RTCService&rtc,Shell&shell){hardware_=&hw;messages_=&messages;settings_=&settings;rtc_=&rtc;shell_=&shell;active_=this;stateSince_=millis();if(!settings.value().enabled){strlcpy(status_,"Disabled",sizeof(status_));return true;}if(!hw.enableRadio()){strlcpy(status_,"SX1262 not detected",sizeof(status_));return false;}configurationChanged();radio.setDio1Action(radioIrq);startReceive();return state_==State::Receiving;}
void MessagingService::configurationChanged(){if(!settings_||!hardware_)return;if(!settings_->value().enabled){if(hardware_->radioAvailable()){radio.clearDio1Action();radio.sleep();}setState(State::Sleeping);strlcpy(status_,"Disabled",sizeof(status_));return;}if(!hardware_->enableRadio())return;radio.setDio1Action(radioIrq);const auto&s=settings_->value();radio.standby();int16_t result=radio.setFrequency(s.frequencyKhz/1000.0);if(result==RADIOLIB_ERR_NONE)result=radio.setBandwidth(125.0);if(result==RADIOLIB_ERR_NONE)result=radio.setSpreadingFactor(s.spreadingFactor);if(result==RADIOLIB_ERR_NONE)result=radio.setCodingRate(5);if(result==RADIOLIB_ERR_NONE)result=radio.setSyncWord(0x39);if(result==RADIOLIB_ERR_NONE)result=radio.setOutputPower(s.powerDbm);if(result==RADIOLIB_ERR_NONE)result=radio.setPreambleLength(12);if(result==RADIOLIB_ERR_NONE)result=radio.setCRC(true);snprintf(status_,sizeof(status_),result==RADIOLIB_ERR_NONE?"Listening %.3f MHz":"Radio configuration error %d",s.frequencyKhz/1000.0,result);if(!suspended_)startReceive();}
void MessagingService::startReceive(){if(!settings_||!settings_->value().enabled||suspended_||!hardware_->radioAvailable()){setState(State::Sleeping);return;}if(radio.startReceive()==RADIOLIB_ERR_NONE)setState(State::Receiving);else{setState(State::Sleeping);strlcpy(status_,"Radio receive error",sizeof(status_));}}
void MessagingService::suspend(){if(suspended_)return;suspended_=true;if(hardware_&&hardware_->radioAvailable()){radio.clearDio1Action();radio.sleep();}setState(State::Sleeping);}
void MessagingService::resume(){if(!suspended_)return;suspended_=false;if(settings_&&settings_->value().enabled&&hardware_->enableRadio()){radio.setDio1Action(radioIrq);configurationChanged();}}
bool MessagingService::send(uint64_t contact,const char*text){if(!settings_||!messages_||!settings_->findContact(contact)||!text||!*text||strlen(text)>MessagingProtocol::kMaxText)return false;uint32_t local=0;return messages_->addOutgoing(contact,settings_->nextMessageId(),nowEpoch(),text,local);}
bool MessagingService::retry(uint32_t localId){auto*m=messages_?messages_->findLocal(localId):nullptr;if(!m||m->direction!=MessageDirection::Outgoing||m->delivery!=MessageDelivery::Failed)return false;return messages_->updateDelivery(localId,MessageDelivery::Queued,0);}
bool MessagingService::startPairing(const char*code){if(!settings_||!code||strlen(code)<6||strlen(code)>16)return false;if(!settings_->value().enabled){settings_->value().enabled=true;settings_->save();}if(!hardware_->enableRadio())return false;strlcpy(pairCode_,code,sizeof(pairCode_));pairing_=true;pairUntil_=millis()+120000;lastPairHello_=0;configurationChanged();strlcpy(status_,"Pairing for 2 minutes",sizeof(status_));return true;}
void MessagingService::stopPairing(){pairing_=false;pairCode_[0]=0;if(settings_&&settings_->value().enabled)strlcpy(status_,"Listening",sizeof(status_));}
void MessagingService::queueAck(uint64_t contact,uint32_t id){ackContact_=contact;ackMessageId_=id;ackPending_=true;}
bool MessagingService::transmit(const uint8_t*packet,size_t length,bool isAck){if(state_==State::Transmitting||millis()<nextTxMs_||!length)return false;memcpy(tx_,packet,length);txLength_=length;sendingAck_=isAck;int16_t result=radio.startTransmit(tx_,txLength_);if(result!=RADIOLIB_ERR_NONE){Serial.printf("[PocketPDA][msg] TX start failed ack=%u err=%d state=%u\n",isAck, result, static_cast<unsigned>(state_));startReceive();return false;}Serial.printf("[PocketPDA][msg] TX start ack=%u bytes=%u\n",isAck,static_cast<unsigned>(length));setState(State::Transmitting);return true;}
bool MessagingService::transmitPending(){auto*m=messages_->nextPending();if(!m||millis()<nextTxMs_)return false;const auto*c=settings_->findContact(m->contactId);if(!c){messages_->updateDelivery(m->localId,MessageDelivery::Failed,m->attempts);Serial.printf("[PocketPDA][msg] TX failed local=%lu: contact missing\n",static_cast<unsigned long>(m->localId));return false;}MessagingProtocol::Header h{MessagingProtocol::Type::Message,settings_->value().deviceId,m->contactId,m->messageId,settings_->nextPacketCounter(),0};size_t length=0;if(!h.counter||!MessagingProtocol::encodeEncrypted(h,c->key,reinterpret_cast<const uint8_t*>(m->text),strlen(m->text),tx_,sizeof(tx_),length)){Serial.printf("[PocketPDA][msg] TX encode failed local=%lu counter=%lu\n",static_cast<unsigned long>(m->localId),static_cast<unsigned long>(h.counter));return false;}currentLocalId_=m->localId;currentAttempts_=m->attempts+1;messages_->updateDelivery(m->localId,MessageDelivery::Sending,currentAttempts_);Serial.printf("[PocketPDA][msg] TX message local=%lu attempt=%u\n",static_cast<unsigned long>(m->localId),static_cast<unsigned>(currentAttempts_));if(transmit(tx_,length,false))return true;messages_->updateDelivery(m->localId,MessageDelivery::Queued,m->attempts);currentLocalId_=0;currentAttempts_=0;ackDeadline_=0;return false;}
void MessagingService::receivePacket(){size_t length=radio.getPacketLength();if(!length||length>sizeof(rx_)){radio.readData(rx_,0);return;}int16_t result=radio.readData(rx_,length);if(result==RADIOLIB_ERR_NONE){++stats_.packetsReceived;processPacket(rx_,length);} }
void MessagingService::processPacket(const uint8_t*p,size_t length){MessagingProtocol::Header h;if(!MessagingProtocol::inspectHeader(p,length,h)||h.sender==settings_->value().deviceId)return;if(h.type==MessagingProtocol::Type::PairHello&&pairing_){char name[24];uint8_t key[32];if(MessagingProtocol::decodePairHello(p,length,pairCode_,h,name,sizeof(name),key)){settings_->upsertContact(h.sender,name,key);snprintf(status_,sizeof(status_),"Paired with %s",name);}return;}if(h.recipient!=settings_->value().deviceId)return;const auto*c=settings_->findContact(h.sender);if(!c)return;uint8_t plain[161]{};size_t plainLength=0;if(!MessagingProtocol::decodeEncrypted(p,length,c->key,h,plain,160,plainLength)){Serial.printf("[PocketPDA][msg] RX decrypt failed type=%u sender=%016llX\n",static_cast<unsigned>(h.type),static_cast<unsigned long long>(h.sender));return;}plain[plainLength]=0;if(h.type==MessagingProtocol::Type::Ack){if(currentLocalId_){auto*m=messages_->findLocal(currentLocalId_);if(m&&m->messageId==h.messageId&&m->contactId==h.sender){Serial.printf("[PocketPDA][msg] ACK local=%lu attempts=%u\n",static_cast<unsigned long>(m->localId),static_cast<unsigned>(currentAttempts_));messages_->updateDelivery(currentLocalId_,MessageDelivery::Delivered,currentAttempts_);currentLocalId_=0;currentAttempts_=0;}}return;}if(h.type==MessagingProtocol::Type::Message){bool duplicate=false;if(messages_->addIncoming(h.sender,h.messageId,nowEpoch(),reinterpret_cast<char*>(plain),duplicate)){Serial.printf("[PocketPDA][msg] RX message id=%lu duplicate=%u\n",static_cast<unsigned long>(h.messageId),duplicate);queueAck(h.sender,h.messageId);if(!duplicate)notifyIncoming(h.sender,reinterpret_cast<char*>(plain));}}}
void MessagingService::notifyIncoming(uint64_t contact,const char*text){shell_->setMessageUnread(messages_->unreadCount());if(!settings_->value().notifications)return;notificationContact_=contact;const auto*c=settings_->findContact(contact);char title[48];snprintf(title,sizeof(title),"MESSAGE - %s",c?c->name:"Pager");char preview[82];strlcpy(preview,text,78);if(strlen(text)>=78)strlcat(preview,"...",sizeof(preview));shell_->notifications().show(title,preview,"OPEN",openMessages,this,47,false);}
void MessagingService::openMessages(void*context){auto*self=static_cast<MessagingService*>(context);if(self->openCallback_)self->openCallback_(self->openContext_,self->notificationContact_);else self->shell_->openApp("messages");}
void MessagingService::onIrq(){if(state_==State::Transmitting){radio.finishTransmit();++stats_.packetsSent;const uint32_t airtimeUs=radio.getTimeOnAir(txLength_);nextTxMs_=millis()+static_cast<uint32_t>((airtimeUs/1000ULL)*99ULL+100);if(!sendingAck_&&currentLocalId_){ackDeadline_=millis()+static_cast<uint32_t>(settings_->value().retrySeconds)*1000UL;setState(State::WaitingAck);}startReceive();return;}receivePacket();startReceive();}
void MessagingService::update(){if(irq_){noInterrupts();irq_=false;interrupts();onIrq();}if(suspended_||!settings_||!settings_->value().enabled)return;uint32_t now=millis();if(pairing_&&int32_t(now-pairUntil_)>=0)stopPairing();if(pairing_&&(lastPairHello_==0||now-lastPairHello_>=5000)&&now>=nextTxMs_&&state_!=State::Transmitting){size_t n=0;if(MessagingProtocol::encodePairHello(settings_->value().deviceId,settings_->value().deviceName,pairCode_,tx_,sizeof(tx_),n)&&transmit(tx_,n,true))lastPairHello_=now;return;}if(ackPending_&&now>=nextTxMs_&&state_!=State::Transmitting){const auto*c=settings_->findContact(ackContact_);if(c){MessagingProtocol::Header h{MessagingProtocol::Type::Ack,settings_->value().deviceId,ackContact_,ackMessageId_,settings_->nextPacketCounter(),0};size_t n=0;const bool encoded=MessagingProtocol::encodeEncrypted(h,c->key,nullptr,0,tx_,sizeof(tx_),n);if(encoded&&transmit(tx_,n,true)){Serial.printf("[PocketPDA][msg] ACK sent id=%lu\n",static_cast<unsigned long>(ackMessageId_));ackPending_=false;}else if(!encoded){Serial.printf("[PocketPDA][msg] ACK encode failed id=%lu\n",static_cast<unsigned long>(ackMessageId_));ackPending_=false;}}else{Serial.printf("[PocketPDA][msg] ACK contact missing id=%016llX\n",static_cast<unsigned long long>(ackContact_));ackPending_=false;}if(ackPending_)return;}if(currentLocalId_&&ackDeadline_&&int32_t(now-ackDeadline_)>=0){Serial.printf("[PocketPDA][msg] ACK timeout local=%lu attempt=%u\n",static_cast<unsigned long>(currentLocalId_),static_cast<unsigned>(currentAttempts_));if(currentAttempts_>=3)messages_->updateDelivery(currentLocalId_,MessageDelivery::Failed,currentAttempts_);else messages_->updateDelivery(currentLocalId_,MessageDelivery::Queued,currentAttempts_);currentLocalId_=0;currentAttempts_=0;ackDeadline_=0;}if(!currentLocalId_&&state_!=State::Transmitting)transmitPending();}
