#pragma once
#ifndef POCKETPDA_UNUSED_RAILS_OFF
#define POCKETPDA_UNUSED_RAILS_OFF 1
#endif
#ifndef POCKETPDA_EXPERIMENTAL_LIGHT_SLEEP
#define POCKETPDA_EXPERIMENTAL_LIGHT_SLEEP 0
#endif
#ifndef POCKETPDA_POWER_DIAGNOSTICS
#define POCKETPDA_POWER_DIAGNOSTICS 1
#endif
#ifndef POCKETPDA_POWER_SD_LOG
#define POCKETPDA_POWER_SD_LOG 1
#endif
